# Site settings
title: Sean的学习博客
SEOTitle: Sean的学习博客 | Sean's Blog
header-img: img/home-bg.jpg
email: tjyangshan@gmail.com
description: "Sean的学习博客"
keyword: "Yang Shan, Sean Yang, Yang Shan的学习博客, Sean's Blog, 博客, 个人网站, 组合优化, 整数规划, 优化理论"
url: ""  
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true
markdown: kramdown

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    seanys
#twitter_username:   huxpro
#facebook_username:  huxpro
linkedin_username:  山-羊-712135141



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: disqus_UwH887dV9F

# Netease settings
netease_comment: true



# Analytics settings
# Baidu Analytics 
ba_track_id: 379602c3382f9ef94b09f71f42e0a374

# Google Analytics
ga_track_id: 'UA-150351185-1'            # Format: UA-xxxxxx-xx
ga_domain: seanys.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "日常学习<br>读文献-写代码-写论文"
sidebar-avatar: "https://tva1.sinaimg.cn/large/006y8mN6ly1g818y88vq0j30u50u0x6p.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
